# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Latest Build/Deploy

on:
  push:
    paths:
      - 'src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dotnet toolkit -> Coree.DotnetTool.ToolKit 
      run: dotnet tool install -g Coree.DotnetTool.ToolKit

    - name: Commandline requirements
      run: |
        toolkit command-exists -t git
        toolkit command-exists -t curl

    - name: set toolkit envars
      run: | 
        toolkit setenv-gitroot -g >> $GITHUB_ENV
        toolkit setenv-gitbranch -g >> $GITHUB_ENV

    - name: Display toolkit envars
      run: |
        echo "${{ env.TOOLKIT_GITROOT }}"
        echo "${{ env.TOOLKIT_GITBRANCH }}"

    # Dotnet tools install powershell
    - name: Dotnet tool install powershell
      run: dotnet tool install --global PowerShell --version 7.4.1

    # Execute powershell workflow.ps1
    - name: Starting the powershell workflow
      run: pwsh .github/workflows/workflow.ps1 "${{ secrets.PAT }}" "${{ secrets.NUGET_PAT }}" "${{ secrets.NUGET_TEST_PAT }}"

